server:
  ip: 100.78.156.148
  port: 9090

spring:
  application:
    name: springboot-minio

  datasource:
    url: jdbc:mysql://100.78.156.148:3306/xie?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xbsg20040619
    driver-class-name: com.mysql.cj.jdbc.Driver

files:
  upload:
    path: D:/home/files/


#自定义配置
minio:
  endpoint: http://100.78.156.148:9000
  accessKey: admin
  secretKey: xbsg20040619
  bucket: user-bucket